### ISSUE TITLE
An Exception with name of network adapter.

### ISSUE THREAD

**Issue by Lensual** [ragnaroks/KcptunGUI#1]
问题重现
![image](https://cloud.githubusercontent.com/assets/11309551/24831399/56653502-1ccb-11e7-8c89-ce27b156d0e2.png)

`ni.Description` 内容和即时窗口中的 `new PerformanceCounterCategory("Network Interface").GetInstanceNames()` 取得的网卡名称不一致

![tim 20170409021650](https://cloud.githubusercontent.com/assets/11309551/24831371/dcfb7cda-1cca-11e7-8503-e8a1cdafeb94.png)

将 `(R)` 修改为 `[R]` 可正常工作

**Comment by ragnaroks** [comment]
这应该是由于设备描述不一致导致的问题,理论上,较罕见

**Comment by ragnaroks** [comment]
fixed,thanks
